export default {
  DROP_FOOD: 'DROP_FOOD',
  KEY_UP_PRESSED: 'KEY_UP_PRESSED',
  KEY_DOWN_PRESSED: 'KEY_DOWN_PRESSED',
  KEY_LEFT_PRESSED: 'KEY_LEFT_PRESSED',
  KEY_RIGHT_PRESSED: 'KEY_RIGHT_PRESSED',
  KEY_SPACE_PRESSED: 'KEY_SPACE_PRESSED',
  SNAKE_DIED: 'SNAKE_DIED',
  SNAKE_EATS: 'SNAKE_EATS',
  SNAKE_MOVES: 'SNAKE_MOVES',
  START_GAME: 'START_GAME'
};
